[package]
name = "leafwing-input-manager"
description = "A straightforward stateful input manager for the Bevy game engine."
version = "0.2.0"
authors = ["Leafwing Studios"]
homepage = "https://leafwing-studios.com/"
repository = "https://github.com/leafwing-studios/leafwing-input-manager"
license = "MIT OR Apache-2.0"
edition = "2021"
categories = ["games", "game-development"]
keywords = ["bevy"]
exclude = ["assets/**/*", "tools/**/*", ".github/**/*"]

[profile.dev]
opt-level = 3

[workspace]
members = ["./", "tools/ci", "macros"]

[dependencies]
bevy = {version = "0.6", default-features = false, features = ["render"]}
petitset = "0.1"
strum = {version = "0.23", features = ["derive"]}
leafwing_input_manager_macros = "0.1"
thiserror = "1.0"

[dev-dependencies]
bevy = {version = "0.6", default-features = true}
derive_more = "0.99"

[lib]
name = "leafwing_input_manager"
path = "src/lib.rs"
